/*
  =====================================================================
   [운영팀 전용] 행사 콘텐츠 데이터 파일
  =====================================================================
  이 파일은 editor.html(콘텐츠 편집기)에서 자동으로 생성되었습니다.
  editor.html을 열어 다시 수정하거나, 이 파일을 텍스트 편집기로 직접 열어
  큰따옴표 안의 값을 고쳐도 됩니다.
  =====================================================================
*/

window.CONTENT = {
  "eventName": "싸이트플래닝 20주년 기념 제주 워크숍",
  "eventSubtitle": "제주 워크숍",
  "date": "2026-10-15",
  "dateDisplay": "2026년 10월 15일(목) ~ 16일(금), 1박 2일",
  "sectionsEnabled": {
    "rainPlan": false,
    "staff": false,
    "meetingSummary": true,
    "checklist": false,
    "faq": false,
    "survey": false,
    "flight": true,
    "location": false
  },
  "heroImage": "",
  "heroTagline": "20주년 기념 제주 워크숍",
  "notice": {
    "active": true,
    "text": "일부 프로그램은 이동 시간이 포함되어 있으며, 상황에 따라 일정이 변경될 수 있습니다."
  },
  "rainPlan": {
    "hasIndoorAlternative": false,
    "description": "",
    "decisionTime": ""
  },
  "contact": {
    "name": "",
    "role": "담당자",
    "phone": ""
  },
  "staff": [],
  "meetingSummary": {
    "time": "08:00",
    "location": "공항 집결 (김포/부산 - 본인 항공편은 항공권 조회에서 확인)",
    "mapUrl": ""
  },
  "schedule": [
    {
      "id": 1,
      "date": "2026-10-15",
      "time": "08:00",
      "endTime": "08:50",
      "title": "공항 집결",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 2,
      "date": "2026-10-15",
      "time": "08:50",
      "endTime": "10:10",
      "title": "부산(서울)→제주",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 3,
      "date": "2026-10-15",
      "time": "10:10",
      "endTime": "10:30",
      "title": "버스 탑승",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 4,
      "date": "2026-10-15",
      "time": "10:30",
      "endTime": "11:00",
      "title": "점심장소로 이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 5,
      "date": "2026-10-15",
      "time": "11:00",
      "endTime": "12:30",
      "title": "점심 식사",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 6,
      "date": "2026-10-15",
      "time": "12:30",
      "endTime": "13:00",
      "title": "이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 7,
      "date": "2026-10-15",
      "time": "13:00",
      "endTime": "15:00",
      "title": "저지문화예술인마을",
      "location": "김창열미술관, 제주현대미술관",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 8,
      "date": "2026-10-15",
      "time": "15:00",
      "endTime": "16:00",
      "title": "본태박물관",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 9,
      "date": "2026-10-15",
      "time": "16:00",
      "endTime": "17:00",
      "title": "이동 및 숙소 배정",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 10,
      "date": "2026-10-15",
      "time": "17:00",
      "endTime": "18:00",
      "title": "연회 오프닝 행사",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 11,
      "date": "2026-10-15",
      "time": "18:00",
      "endTime": "19:00",
      "title": "저녁 식사",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 12,
      "date": "2026-10-15",
      "time": "19:00",
      "endTime": "20:00",
      "title": "20주년 기념 이벤트",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 13,
      "date": "2026-10-16",
      "time": "07:00",
      "endTime": "09:30",
      "title": "조식 & 개인 일정",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 14,
      "date": "2026-10-16",
      "time": "09:30",
      "endTime": "10:00",
      "title": "집합",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 15,
      "date": "2026-10-16",
      "time": "10:00",
      "endTime": "12:00",
      "title": "제주 오름 투어",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 16,
      "date": "2026-10-16",
      "time": "12:00",
      "endTime": "13:30",
      "title": "점심 식사",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 17,
      "date": "2026-10-16",
      "time": "13:30",
      "endTime": "14:00",
      "title": "이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 18,
      "date": "2026-10-16",
      "time": "14:00",
      "endTime": "16:00",
      "title": "시너지&리프레시 프로그램",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 19,
      "date": "2026-10-16",
      "time": "16:00",
      "endTime": "17:00",
      "title": "공항 이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 20,
      "date": "2026-10-16",
      "time": "18:55",
      "endTime": "20:25",
      "title": "제주→부산(서울)",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    }
  ],
  "locations": [],
  "mapEmbedQuery": "",
  "checklist": [],
  "faq": [],
  "survey": {
    "url": "",
    "duration": ""
  },
  "flight": {
    "formUrl": "",
    "notice": "본인 성함으로 조회하면 항공편과 예약번호를 확인하실 수 있습니다.",
    "records": [
      {
        "name": "김혜경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "임진성",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "조혜원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "유지우",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "배은경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "",
        "returnAirline": "",
        "returnTime": "",
        "returnLocation": "",
        "returnFlight": "",
        "returnReservation": ""
      },
      {
        "name": "김채은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "SHI YUNSHU",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "유성",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "GDL7UW"
      },
      {
        "name": "박경민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "라현필",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "RGF74N"
      },
      {
        "name": "임지홍",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "박종원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "NE6CHG"
      },
      {
        "name": "장종구",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "L7DIPL",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "NE6CHG"
      },
      {
        "name": "전주협",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/17(토)",
        "returnAirline": "제주항공",
        "returnTime": "18:35",
        "returnLocation": "제주",
        "returnFlight": "7C132",
        "returnReservation": "KGMCFK"
      },
      {
        "name": "오지환",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/17(토)",
        "returnAirline": "제주항공",
        "returnTime": "18:35",
        "returnLocation": "제주",
        "returnFlight": "7C132",
        "returnReservation": "KGMCFK"
      },
      {
        "name": "김지언",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "강정민",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "KONDURI SAI BHANU SREENIDHI",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "조혜빈",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "정재희",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김우정",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김지원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "황수경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "박수정",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "조연주",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "강다현",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "박재영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김태훈",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김표성",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "양재원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김범준",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "심지윤",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "강병현",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "J81GFI",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김종민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "정의근",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "박진형",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "DDVV67"
      },
      {
        "name": "임채은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "52E5UH"
      },
      {
        "name": "한영숙",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DHEQNX",
        "returnDate": "",
        "returnAirline": "",
        "returnTime": "",
        "returnLocation": "",
        "returnFlight": "",
        "returnReservation": ""
      },
      {
        "name": "신나은",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김용민",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김은지",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "조현실",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김수영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "이세영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "양채은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "백인영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "J81GFI",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "최유진",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "박규빈",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김희은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김지현",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "이슬기",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "정민경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "정지은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "최인영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "이창민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "최재영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김정한",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "전성은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "허민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "하동근",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "박현지",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "J81GFI",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "문서연",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "장윤지",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "장민석",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "제창휘",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "박주혁",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김동환",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "조성호",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "배찬우",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DHEQNX",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EZ8BHF"
      }
    ]
  }
};
