/*
  =====================================================================
   [운영팀 전용] 행사 콘텐츠 데이터 파일
  =====================================================================
  이 파일은 editor.html(콘텐츠 편집기)에서 자동으로 생성되었습니다.
  editor.html을 열어 다시 수정하거나, 이 파일을 텍스트 편집기로 직접 열어
  큰따옴표 안의 값을 고쳐도 됩니다.
  =====================================================================
*/

window.CONTENT = {
  "eventName": "싸이트플래닝 20주년 기념 제주 워크숍",
  "eventSubtitle": "제주 워크숍",
  "date": "2026-10-15",
  "dateDisplay": "2026년 10월 15일(목) ~ 16일(금), 1박 2일",
  "sectionsEnabled": {
    "rainPlan": false,
    "staff": false,
    "meetingSummary": true,
    "checklist": false,
    "faq": false,
    "survey": false,
    "flight": true,
    "bus": true,
    "rooms": true,
    "location": false
  },
  "heroImage": "images/싸이트플래닝-메인-사진.png",
  "heroTagline": "20주년 기념 제주 워크숍",
  "heroBanner": true,
  "notice": {
    "active": true,
    "text": "일부 프로그램은 이동 시간이 포함되어 있으며, 상황에 따라 일정이 변경될 수 있습니다."
  },
  "rainPlan": {
    "hasIndoorAlternative": false,
    "description": "",
    "decisionTime": ""
  },
  "contact": {
    "name": "",
    "role": "담당자",
    "phone": ""
  },
  "staff": [],
  "meetingSummary": {
    "time": "07:30",
    "location": "공항 집결 (김포/부산 - 본인 항공편은 항공권 조회에서 확인)",
    "mapUrl": ""
  },
  "schedule": [
    {
      "id": 1,
      "date": "2026-10-15",
      "time": "07:30",
      "endTime": null,
      "title": "공항 집결",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 2,
      "date": "2026-10-15",
      "time": "08:50",
      "endTime": "10:10",
      "title": "부산(서울)→제주",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 3,
      "date": "2026-10-15",
      "time": "10:10",
      "endTime": null,
      "title": "버스 탑승",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "제주공항 도착 후 버스 탑승 안내\n\n제주공항 도착 후, 공항 내 안내 스태프의 안내에 따라 버스 주차장으로 이동해 주시기 바랍니다.\n버스 주차장 도착 후 지정된 버스에 탑승해 주시기 바랍니다.",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": "images/schedule-3-공항-내부-동선.png",
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 4,
      "date": "2026-10-15",
      "time": "11:00",
      "endTime": "12:30",
      "title": "점심 식사",
      "location": "이금돈지",
      "mapUrl": "https://maps.app.goo.gl/JrkiRQbqiEXpyxXw6",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 5,
      "date": "2026-10-15",
      "time": "12:30",
      "endTime": "13:00",
      "title": "이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 6,
      "date": "2026-10-15",
      "time": "13:00",
      "endTime": "15:00",
      "title": "저지문화예술인마을",
      "location": "김창열미술관, 제주현대미술관",
      "mapUrl": "https://maps.app.goo.gl/CHBGfnaf9ZPDnPvH6",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 7,
      "date": "2026-10-15",
      "time": "15:00",
      "endTime": "16:00",
      "title": "본태박물관",
      "location": "",
      "mapUrl": "https://maps.app.goo.gl/oDbK1z5VNgaNF9wf7",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 8,
      "date": "2026-10-15",
      "time": "16:00",
      "endTime": "17:00",
      "title": "이동 및 숙소 배정(방 배정 탭에서 객실 넘버 확인 가능합니다)",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": "images/schedule-8-야크마을-지도.jpeg",
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 9,
      "date": "2026-10-15",
      "time": "17:00",
      "endTime": "18:00",
      "title": "연회 오프닝 행사",
      "location": "야크마을 연회장",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 10,
      "date": "2026-10-15",
      "time": "18:00",
      "endTime": "19:00",
      "title": "저녁 식사",
      "location": "야크마을 연회장",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 11,
      "date": "2026-10-15",
      "time": "19:00",
      "endTime": "20:00",
      "title": "20주년 기념 이벤트",
      "location": "야크마을 연회장",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 12,
      "date": "2026-10-16",
      "time": "07:00",
      "endTime": "09:30",
      "title": "조식 & 개인 일정",
      "location": "야크마을 두도레스토랑",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 13,
      "date": "2026-10-16",
      "time": "09:30",
      "endTime": "10:00",
      "title": "집합",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 14,
      "date": "2026-10-16",
      "time": "10:00",
      "endTime": "12:00",
      "title": "제주 오름 투어",
      "location": "새별오름",
      "mapUrl": "https://maps.app.goo.gl/WztyyQipWbf7Z2R58",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 15,
      "date": "2026-10-16",
      "time": "12:00",
      "endTime": "13:30",
      "title": "점심 식사",
      "location": "열흘 흑돼지(한림협재점)",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 16,
      "date": "2026-10-16",
      "time": "13:30",
      "endTime": "14:00",
      "title": "이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 17,
      "date": "2026-10-16",
      "time": "14:00",
      "endTime": "16:00",
      "title": "시너지&리프레시 프로그램",
      "location": "9.81파크",
      "mapUrl": "https://maps.app.goo.gl/ChTJMhcMB9aefEAPA",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 18,
      "date": "2026-10-16",
      "time": "16:00",
      "endTime": "17:00",
      "title": "공항 이동",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    },
    {
      "id": 19,
      "date": "2026-10-16",
      "time": "18:55",
      "endTime": "20:25",
      "title": "제주→부산(서울)",
      "location": "",
      "mapUrl": "",
      "voteUrl": "",
      "description": "",
      "travelTimeToNext": null,
      "difficulty": null,
      "distance": null,
      "meal": null,
      "freeTimeRecommendation": null,
      "photo": null,
      "photoUpload": {
        "enabled": false,
        "formUrl": "",
        "driveFolderUrl": "",
        "description": "",
        "showGallery": false
      }
    }
  ],
  "locations": [],
  "mapEmbedQuery": "",
  "checklist": [],
  "faq": [],
  "survey": {
    "url": "",
    "duration": ""
  },
  "flight": {
    "formUrl": "",
    "notice": "본인 성함으로 조회하면 항공편과 예약번호를 확인하실 수 있습니다.",
    "records": [
      {
        "name": "김혜경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "임진성",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "조혜원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "유지우",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "배은경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "",
        "returnAirline": "",
        "returnTime": "",
        "returnLocation": "",
        "returnFlight": "",
        "returnReservation": ""
      },
      {
        "name": "김채은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "SHI YUNSHU",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "유성",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "GDL7UW"
      },
      {
        "name": "박경민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "라현필",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "RGF74N"
      },
      {
        "name": "임지홍",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "PJ282R"
      },
      {
        "name": "박종원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "NE6CHG"
      },
      {
        "name": "장종구",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "L7DIPL",
        "returnDate": "10/16(금)",
        "returnAirline": "제주항공",
        "returnTime": "18:55",
        "returnLocation": "제주",
        "returnFlight": "7C186",
        "returnReservation": "NE6CHG"
      },
      {
        "name": "전주협",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/17(토)",
        "returnAirline": "제주항공",
        "returnTime": "18:35",
        "returnLocation": "제주",
        "returnFlight": "7C132",
        "returnReservation": "KGMCFK"
      },
      {
        "name": "오지환",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:55",
        "departureLocation": "김포",
        "departureFlight": "7C109",
        "departureReservation": "G8R9VF",
        "returnDate": "10/17(토)",
        "returnAirline": "제주항공",
        "returnTime": "18:35",
        "returnLocation": "제주",
        "returnFlight": "7C132",
        "returnReservation": "KGMCFK"
      },
      {
        "name": "김지언",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "강정민",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "KONDURI SAI BHANU SREENIDHI",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "조혜빈",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "정재희",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김우정",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김지원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "황수경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "박수정",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "조연주",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "강다현",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "박재영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김태훈",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김표성",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "양재원",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김범준",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "심지윤",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "강병현",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "J81GFI",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "김종민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "정의근",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EYFEC4"
      },
      {
        "name": "박진형",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "DDVV67"
      },
      {
        "name": "임채은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/16(금)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "52E5UH"
      },
      {
        "name": "한영숙",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DHEQNX",
        "returnDate": "",
        "returnAirline": "",
        "returnTime": "",
        "returnLocation": "",
        "returnFlight": "",
        "returnReservation": ""
      },
      {
        "name": "신나은",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김용민",
        "departureDate": "",
        "departureAirline": "",
        "departureTime": "",
        "departureLocation": "",
        "departureFlight": "",
        "departureReservation": "",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김은지",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "조현실",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김수영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "이세영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "양채은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "백인영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "J81GFI",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "최유진",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "박규빈",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김희은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김지현",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "이슬기",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "정민경",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "정지은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "최인영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "이창민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "최재영",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김정한",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "전성은",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "허민",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "하동근",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "박현지",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "J81GFI",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "문서연",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "장윤지",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "장민석",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "제창휘",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "박주혁",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DBKJUZ",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "김동환",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "조성호",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DJWGUB",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "ERVU7Y"
      },
      {
        "name": "배찬우",
        "departureDate": "10/15(목)",
        "departureAirline": "제주항공",
        "departureTime": "08:50",
        "departureLocation": "부산",
        "departureFlight": "7C503",
        "departureReservation": "DHEQNX",
        "returnDate": "10/17(토)",
        "returnAirline": "대한항공",
        "returnTime": "19:25",
        "returnLocation": "제주",
        "returnFlight": "KE1554",
        "returnReservation": "EZ8BHF"
      }
    ]
  },
  "bus": {
    "notice": "이름을 검색하면 버스 호차를 확인하실 수 있습니다.",
    "groups": [
      {
        "label": "1호차",
        "date": "",
        "members": [
          "한영숙 (2일차 제외)",
          "조현실",
          "김지원",
          "김은지",
          "정지은",
          "최인영",
          "백인영",
          "박현지",
          "심지윤",
          "박수정",
          "김범준",
          "문서연",
          "조연주",
          "강다현",
          "조성호",
          "박규빈",
          "김지현",
          "니디 (KONDURI SAI BHANU SREENIDHI)",
          "하동근",
          "조혜빈",
          "박재영",
          "김표성",
          "김수영",
          "이세영",
          "양채은",
          "배은경",
          "김채은",
          "김혜경",
          "유성",
          "전주협",
          "오지환",
          "박경민",
          "장종구"
        ]
      },
      {
        "label": "2호차",
        "date": "",
        "members": [
          "배찬우",
          "김정한",
          "박진형",
          "김동환",
          "장윤지",
          "정민경",
          "임채은",
          "김종민",
          "정의근",
          "박주혁",
          "김희은",
          "전성은",
          "허민",
          "최재영",
          "강병현",
          "황수경",
          "이슬기",
          "정재희",
          "김우정",
          "김태훈",
          "양재원",
          "이창민",
          "최유진",
          "제창휘",
          "장민석",
          "조혜원",
          "사운주 (SHI YUNSHU)",
          "임진성",
          "유지우",
          "라현필",
          "임지홍",
          "박종원"
        ]
      }
    ]
  },
  "rooms": {
    "notice": "이름을 검색하면 야크마을 객실 넘버를 확인하실 수 있습니다.",
    "groups": [
      {
        "label": "1호",
        "date": "10/14(수)",
        "members": [
          "김지언",
          "강정민",
          "신나은",
          "김용민"
        ]
      },
      {
        "label": "1호",
        "date": "10/15(목)",
        "members": [
          "정의근",
          "김종민",
          "박주혁"
        ]
      },
      {
        "label": "2호",
        "date": "10/15(목)",
        "members": [
          "최재영",
          "김용민",
          "유성",
          "김정한"
        ]
      },
      {
        "label": "3호",
        "date": "10/15(목)",
        "members": [
          "김표성",
          "김태훈",
          "박재영",
          "양재원"
        ]
      },
      {
        "label": "4호",
        "date": "10/15(목)",
        "members": [
          "하동근",
          "허민",
          "전성은",
          "심지윤"
        ]
      },
      {
        "label": "5호",
        "date": "10/15(목)",
        "members": [
          "전주협",
          "오지환",
          "장종구"
        ]
      },
      {
        "label": "6호",
        "date": "10/15(목)",
        "members": [
          "박종원",
          "박경민",
          "라현필",
          "임지홍"
        ]
      },
      {
        "label": "7호",
        "date": "10/15(목)",
        "members": [
          "임진성"
        ]
      },
      {
        "label": "8호",
        "date": "10/15(목)",
        "members": [
          "김동환",
          "박진형",
          "조성호",
          "강병현"
        ]
      },
      {
        "label": "9호",
        "date": "10/15(목)",
        "members": [
          "이세영",
          "김수영",
          "양채은",
          "최유진"
        ]
      },
      {
        "label": "10호",
        "date": "10/15(목)",
        "members": [
          "임채은",
          "정지은",
          "최인영",
          "정민경"
        ]
      },
      {
        "label": "11호",
        "date": "10/15(목)",
        "members": [
          "박현지",
          "백인영",
          "박수정"
        ]
      },
      {
        "label": "12호",
        "date": "10/15(목)",
        "members": [
          "강다현",
          "장윤지",
          "조연주",
          "문서연"
        ]
      },
      {
        "label": "13호",
        "date": "10/15(목)",
        "members": [
          "김희은",
          "박규빈",
          "김지현",
          "니디 (KONDURI SAI BHANU SREENIDHI)"
        ]
      },
      {
        "label": "14호",
        "date": "10/15(목)",
        "members": [
          "김우정",
          "강정민",
          "정재희",
          "조혜빈"
        ]
      },
      {
        "label": "15호",
        "date": "10/15(목)",
        "members": [
          "이슬기",
          "김지언",
          "황수경",
          "김지원"
        ]
      },
      {
        "label": "16호",
        "date": "10/15(목)",
        "members": [
          "김범준",
          "이창민",
          "배찬우",
          "장민석",
          "제창휘"
        ]
      },
      {
        "label": "17호",
        "date": "10/15(목)",
        "members": [
          "배은경",
          "김채은",
          "사운주 (SHI YUNSHU)",
          "김혜경",
          "조혜원",
          "유지우"
        ]
      },
      {
        "label": "18호",
        "date": "10/15(목)",
        "members": [
          "조현실",
          "신나은",
          "한영숙",
          "김은지"
        ]
      }
    ]
  }
};
